# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='demo',
  syntax='proto3',
  serialized_options=_b('B\004DemoP\001'),
  serialized_pb=_b('\n\ndemo.proto\x12\x04\x64\x65mo\";\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x1c\n\x06\x63\x61nvas\x18\x03 \x01(\x0b\x32\x0c.demo.Canvas\"\'\n\x06\x43\x61nvas\x12\r\n\x05width\x18\x01 \x01(\x03\x12\x0e\n\x06height\x18\x02 \x01(\x03\x32\x33\n\tTransform\x12&\n\x04\x66lip\x12\x0b.demo.Point\x1a\x0b.demo.Point\"\x00(\x01\x30\x01\x42\x08\x42\x04\x44\x65moP\x01\x62\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='demo.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='demo.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='demo.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canvas', full_name='demo.Point.canvas', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=79,
)


_CANVAS = _descriptor.Descriptor(
  name='Canvas',
  full_name='demo.Canvas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='demo.Canvas.width', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='demo.Canvas.height', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=120,
)

_POINT.fields_by_name['canvas'].message_type = _CANVAS
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Canvas'] = _CANVAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Point)
  })
_sym_db.RegisterMessage(Point)

Canvas = _reflection.GeneratedProtocolMessageType('Canvas', (_message.Message,), {
  'DESCRIPTOR' : _CANVAS,
  '__module__' : 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.Canvas)
  })
_sym_db.RegisterMessage(Canvas)


DESCRIPTOR._options = None

_TRANSFORM = _descriptor.ServiceDescriptor(
  name='Transform',
  full_name='demo.Transform',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=122,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='flip',
    full_name='demo.Transform.flip',
    index=0,
    containing_service=None,
    input_type=_POINT,
    output_type=_POINT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSFORM)

DESCRIPTOR.services_by_name['Transform'] = _TRANSFORM

# @@protoc_insertion_point(module_scope)
