# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.demo_pb2 as demo__pb2


class TransformStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.flip = channel.stream_stream(
        '/demo.Transform/flip',
        request_serializer=demo__pb2.Point.SerializeToString,
        response_deserializer=demo__pb2.Point.FromString,
        )


class TransformServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def flip(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransformServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'flip': grpc.stream_stream_rpc_method_handler(
          servicer.flip,
          request_deserializer=demo__pb2.Point.FromString,
          response_serializer=demo__pb2.Point.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.Transform', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
